# Generated by Django 4.1.5 on 2023-01-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity_app", "0002_entity_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="description",
            field=models.TextField(
                default="A description of this entity that will be replaced."
            ),
        ),
    ]
