# Generated by Django 4.1.5 on 2023-01-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity_app", "0003_entity_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="wikidata_id",
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
