# Generated by Django 4.1.5 on 2023-01-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "entity_app",
            "0005_entity_access_entity_created_at_entity_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="wikidata_id",
            field=models.CharField(
                default="no-wikidata-id", editable=False, max_length=16
            ),
            preserve_default=False,
        ),
    ]
